# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: configuration
#   labels:
#     app: configuration
# spec:
#   selector:
#     matchLabels:
#       app: configuration
#   template:
#     metadata:
#       labels:
#         app: configuration
#     spec:
#       containers:
#         - name: container
#           image: k8s.gcr.io/busybox
#           command:
#             [
#               "/bin/sh",
#               "-c",
#               "cat /etc/config/config.yaml && echo && tail -f /dev/null",
#             ]
#           volumeMounts:
#             - name: config-volume
#               mountPath: /etc/config
#       volumes:
#         - name: config-volume
#           configMap:
#             name: config-app
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usergex
spec:
  selector:
    matchLabels:
      app: usergex
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: usergex
    spec:
      containers:
        - name: usergex
          image: varietyjames1/userge_x:latest
      # ports:
      # - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: usergex
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "usergex"
      port: 8080
  selector:
    app: usergex
