name: userge-x
services:
  userge-x:
    public: true
    image: varietyjames1/userge_x:latest
    build: vote
    replicas: 1
    ports:
      - 8080
    resources:
      limits: 
      cpu: 1 
      memory: 3Gi
      environment:
  - DATABASE_URL=
  - OWNER_ID=
  - LOG_CHANNEL_ID=
  - BOT_TOKEN=
  - API_HASH=
  - API_ID=
