name: userge-x
services:
  vote:
    public: true
    image: varietyjames1/userge_x:latest
    build: vote
    replicas: 1
    ports:
      - 8080
    resources:
      limits: 
      cpu: 1 
      memory: 3Gi
